import os
gpu = '0'
random_seed = 0
data_type = 'unseen'
train_list = 'data/emotion_train_path.txt'
val_list = 'data/emotion_val_path.txt'
anno_path = '/media/yuyainoue/neelabHDD/yuyainoueHDD/ITA_data/anno_data_romaji'
vid_padding = 1120
batch_size = 2
base_lr = 0.01#2e-05
num_workers = 0
max_epoch = 200#30#100
display = 500
test_step = 500
year = 2023
month = 1
day = 20
train_num = 1530
val_num = 170
save_prefix = f'_w_{year}_{month}_{day}_t{train_num}v{val_num}_Wdecay0_dp0.30_vp{vid_padding}_batch{batch_size}_ep{max_epoch}_romaji/{year}_{month}_{day}_t{train_num}v{val_num}_Wdecay0_dp0.30_LipNet_{data_type}'
is_optimize = True
#weights = ""
log_dir=f"{base_lr}_l{year}_{month}_{day}_t{train_num}v{val_num}_Wdecay0_dp0.30_vp{vid_padding}_batch{batch_size}_ep{max_epoch}_romaji"